services:
  # Backend service - Java Spring Boot application
  contoso-backend:
    build:
      context: .
      dockerfile: Dockerfile.java
    container_name: contoso-backend
    ports:
      - "8080:8080"
    environment:
      - CODESPACE_NAME=${CODESPACE_NAME}
      - GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN=${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
    networks:
      - contoso
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend service - .NET Blazor application
  contoso-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dotnet
    container_name: contoso-frontend
    ports:
      - "3030:8080"
    environment:
      - ApiSettings__BaseUrl=http://contoso-backend:8080/api
    networks:
      - contoso
    depends_on:
      contoso-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Custom network for service communication
networks:
  contoso:
    driver: bridge
